# Allow lines to be as long as 120.
line-length = 118

[lint]
select = ["ALL"]
ignore = ["COM812"] # this rules causes conflicts, ruff advise to ignore it.

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

pydocstyle = { convention = "numpy" }

[lint.per-file-ignores]
"tests/test_*.py" = [
    "S101", # asserts allowed in tests
    # "PLR2004", # Magic value used in comparison in tests
    # "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
]
"example.py" = [
    "T201"
]

[format]
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true
docstring-code-line-length = "dynamic"
